Vagrant.configure(2) do |config|
  config.vm.box = "geerlingguy/ubuntu1604"

  config.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh"
  config.vm.network "forwarded_port", guest: 80, host: 8888

  config.vm.provider :virtualbox do |vb|
        vb.name = "VoimalaVM"

        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "deploy.yml"
  end
end